version: "3.5"

services:
  fronted:
    build: ReactJsFrontend
    ports:
      - 3000:3000
    volumes:
      - ./ReactJsFrontend/src:/code/src
      - /ReactJsFrontend/node_modules
  backend:
    container_name: DjangoBackend
    build:
      context: .
      dockerfile: DjangoBackend/Dockerfile
    command: python3 DjangoBackend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
